version: '3.3'
services:
  rates-postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=ratesservicedb_lite
    ports:
    - 5432:5432
    volumes:
    - ./postgreSQL/init-db.sql:/docker-entrypoint-initdb.d/init.sql
  rates-wiremock:
    image: wiremock/wiremock:latest
    ports:
    - '7070:8080'
    - '7443:8443'
    volumes:
    - ./wiremock/__files:/home/wiremock/__files
    - ./wiremock/mappings:/home/wiremock/mappings
