version: '3.3'
services:
  rates-postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=ratesservicedb_lite
    ports:
    - 5432:5432
    volumes:
    - ./postgreSQL/init-db.sql:/docker-entrypoint-initdb.d/init.sql